config/urls.py
# config/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('portfolio.urls')),
]

portfolio/urls.py
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from config import settings
from . import views

from django.urls import path

from portfolio.views import *

app_name = 'portfolio'
name = "home"

urlpatterns = [
                  path('', views.home_page_view, name=''),
                  path('home/', views.home_page_view, name='home'),
                  path('licenciatura/', views.licenciatura_page_view, name='licenciatura'),
                  path('blog/', views.blog_page_view, name='blog'),
                  path('post_detail/<slug:slug>/', views.post_detail, name='post_detail'),
                  path('programacao/', views.programacao_page_view, name='programacao'),
                  path('virtualizacao/', views.virtualizacao_page_view, name='virtualizacao'),
                  path('reverse/', views.reverse_page_view, name='reverse'),
                  path('login/', views.login_page_view, name='login'),
                  path('logout/', views.logoutPage, name='logout'),
                  path('register/', views.registerPage, name='register'),
                  path('quizz/', views.quizz_page_view, name='quizz'),
                  path('api/', views.api_page_view, name='api'),
                  path('pw/', views.pw_page_view, name='pw'),
                  path('educacao/', views.educacao_page_view, name='educacao'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

# não tendo este static em cima fez com que eu não pudesse fazer nada e tive que refazer o código todo

#para imagens
if settings.DEBUG:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

portfolio/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Portfolio(models.Model):
    name = models.CharField(max_length=100)
    id = models.CharField(max_length=8, primary_key=True)


class Post(models.Model):
    title = models.CharField(max_length=300, unique=True)
    slug = models.SlugField(None)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(None)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_added']


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['date_added']


class Projetos(models.Model):
    gitLink = models.CharField(default="https://github.com/rodrigoamaro22004525", max_length=200)
    nome = models.CharField(max_length=50)
    linguagens = models.CharField(max_length=50)
    img = models.ImageField(upload_to='media/', null=True)

    def __str__(self):
        return self.nome


class pontuacaoquizz(models.Model):
    name = models.CharField(User, max_length=50, blank=True)

    Q1 = models.CharField(null=True, max_length=200)
    Q2 = models.CharField(null=True, max_length=200)
    Q3 = models.CharField(null=True, max_length=200)
    Q4 = models.CharField(null=True, max_length=200)

    def __str__(self):
        return self.name

    """
        Q1 -> Qual o animal que a google aluga para o seu uso (cabra)
        Q2 -> Quando foi inventado o Keyboard do estilo QWERTY (1868)
        Q3 -> De que material foi feito o primeiro rato (madeira)
        Q4 -> Qual foi o primeiro tweet da google? (I’m 01100110 01100101 01100101 01101100 01101001 01101110 01100111 00100000 01101100 01110101 01100011 01101011 01111001 00001010)
        """


class media(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='Quizz/', blank=True)


class licenciatura(models.Model):
    nomeCadeira = models.CharField(max_length=50)
    semestre = models.IntegerField(default=1)
    etcs = models.IntegerField(default=0)
    link_cadeira = models.URLField(blank=True)
    rank = models.CharField(max_length=6)
    ano = models.IntegerField(default=1)
    """⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐"""

    def __str__(self):
        return self.nomeCadeira


# programação web
class noticias(models.Model):
    titulo = models.CharField(max_length=50)
    descricao = models.CharField(max_length=300)
    img = models.ImageField(upload_to='media/', null=True)
    linkNot = models.URLField(max_length=200, blank=True)

    def __str__(self):
        return self.titulo


class tecnologias(models.Model):
    nome = models.CharField(max_length=50)
    acronimo = models.CharField(max_length=5)
    date = models.DateTimeField(default=datetime.now, blank=True)
    autor = models.CharField(max_length=50)
    logo = models.ImageField(upload_to='media/', null=True)
    linkYo = models.CharField(max_length=200, default="https://github.com/rodrigoamaro22004525?tab=repositories")
    descricao = models.CharField(max_length=400)

    def __str__(self):
        return self.nome

# programação web

portfolio/forms.py
from .models import *
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome do Autor'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'email do Autor'}),
            'body': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'comentário do Autor'}),
        }

        labels = {
            'name': 'Name',
            'email': 'Email',
            'body': 'Body',
        }


# codigo inutil
class ProjetosForm(forms.ModelForm):
    class Meta:
        model = Projetos
        fields = '__all__'

        # ferramentas
        widgets = {

        }

        help_texts = {

        }

        labels = {

            'nome': 'Insira o nome',
            'data': 'Data',
            'imagem': 'Insira a sua imagem',

        }


# codigo inutil

class createuserform(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2',)

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'username'}),
            'password1': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'password'}),
            'password2': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'password'}),
        }

        labels = {
            'username': 'Username',
            'password1': 'Password1',
            'password2': 'Password2',
        }


class PontuacaoQuizzForm(forms.ModelForm):
    class Meta:
        model = pontuacaoquizz
        fields = ['Q1', 'Q2', 'Q3', 'Q4']

        """
            Q1 -> Qual o animal que a google aluga para o seu uso (cabra)
            Q2 -> Quando foi inventado o Keyboard do estilo QWERTY (1868)
            Q3 -> De que material foi feito o primeiro rato (madeira)
            Q4 -> Qual foi o primeiro tweet da google? (I’m 01100110 01100101 01100101 01101100 01101001 01101110 01100111 00100000 01101100 01110101 01100011 01101011 01111001 00001010)
        """

        widgets = {
            'Q1': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Q1'}),
            'Q2': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Q2'}),
            'Q3': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Q3'}),
            'Q4': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Q4'}),
        }

        labels = {
            'Q1': 'Qual o animal que a google aluga para o seu uso?',
            'Q2': 'Quando foi inventado o Keyboard do estilo QWERTY?',
            'Q3': 'De que material foi feito o primeiro rato?',
            'Q4': 'Qual foi o primeiro tweet da google?',
        }


class licenciaturaForm(forms.ModelForm):
    class Meta:
        model = licenciatura
        fields = '__all__'

        widgets = {
            'nomeCadeira': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome da Cadeira'}),
            'semestre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Semestre'}),
            'etcs': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nr de ETC\'s'}),
            'link_cadeira': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'URL da Cadeira'}),
        }

        labels = {
            'nomeCadeira': 'NomeDaCadeira',
            'semestre': 'Semestre',
            'etcs': 'Etcs',
            'link_cadeira': 'LinkDaCadeira',
        }


class noticia(forms.ModelForm):
    class Meta:
        model = noticias
        fields = '__all__'

        widgets = {

        }

        labels = {
            'titulo': 'Titulo',
            'descricao': 'Descricao',
            'img': 'Img',
            'linkNot': 'LinkNot',
        }


class tecnologia(forms.ModelForm):
    class Meta:
        model = tecnologias
        fields = '__all__'

        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome da Tecnologia'}),
            'acronimo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'acronimo'}),
            'ano': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ano'}),
            'autor': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'autor'}),
            'logo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'logo'}),
            'linkYo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'link da tecnologia'}),
            'descricao': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'descricao da tecnologia'}),
        }

        labels = {
            'nome': 'Nome',
            'acronimo': 'Acronimo',
            'ano': 'Ano',
            'autor': 'Autor',
            'logo': 'Logo',
            'linkYo': 'LinkYo',
            'descricao': 'Descricao',
        }

portfolio/views.py
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from .forms import *
from .functions import desenha_grafico_resultados
from .models import *


# Create your views here.
def home_page_view(request):
    current_user = request.user
    user_id = current_user.id
    context = {'user_id': user_id}
    return render(request, 'portfolio/home.html', context)


# Create your views here.
def apresentacao_page_view(request):
    return render(request, 'portfolio/layout.html')


# Licenciatura
def licenciatura_page_view(request):
    context = {
        "cadeiras": licenciatura.objects.all(),
    }
    return render(request, 'portfolio/licenciatura.html', context)


#  blog
def blog_page_view(request):
    posts = Post.objects.all()
    return render(request, 'portfolio/blog.html', {'posts': posts})


# virtualização
def virtualizacao_page_view(request):
    return render(request, 'portfolio/virtualizacao.html')


# Reverse-Eng
def reverse_page_view(request):
    return render(request, 'portfolio/reverse.html')


# detail
def post_detail(request, slug):
    post = Post.objects.get(slug=slug or None)

    if request.method == 'POST':
        form = CommentForm(request.POST or None, request.FILES)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()

        return redirect('portfolio:post_detail', slug=post.slug)
    else:
        form = CommentForm()

    return render(request, 'portfolio/post_detail.html', {'post': post, 'form': form})


# projetos/programação
def programacao_page_view(request):
    projetos = {'programacao': Projetos.objects.all()}

    return render(request, 'portfolio/programacao.html', projetos)


def registerPage(request):
    if request.method == 'POST':
        form = createuserform(request.POST)
        if form.is_valid():
            user = form.save()
            # refresh no valores do field
            user.refresh_from_db()

            # save no utilizador
            user.save()

            # palavra-passe dele para ser autenticado e levado po "home" automaticamente
            raw_password = form.cleaned_data.get('password1')

            # login depois de criar a conta
            user = authenticate(username=user.username, password=raw_password)

            login(request, user)

            return redirect('portfolio:home')
    else:
        form = createuserform()
    return render(request, 'portfolio/register.html', {'form': form})


def login_page_view(request):
    if request.user.is_authenticated:
        return redirect('portfolio:home')
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
        context = {}
        return render(request, 'portfolio/login.html', context)


@login_required
def logoutPage(request):
    logout(request)
    return redirect('/')


def quizz_page_view(request):
    if not request.user.is_authenticated:
        messages.error(request, 'Utilizador não efetuou login')

        return redirect('portfolio:home')
    else:
        form = PontuacaoQuizzForm(request.POST)
        user = User.objects.get(username=request.user.get_username())

        if request.method == 'POST':
            if form.is_valid():
                form = form.save(commit=False)
                form.name = user.username
                form.save()
                desenha_grafico_resultados(pontuacaoquizz.objects.all())
                return HttpResponseRedirect(request.path_info)

        else:
            context = {
                'form': form,
            }
            return render(request, 'portfolio/quizz.html', context)


def api_page_view(request):
    return render(request, 'portfolio/api.html')


def pw_page_view(request):
    context = {'noticias': noticias.objects.all(), 'tecnologias': tecnologias.objects.all()}

    return render(request, 'portfolio/pw.html', context)


def educacao_page_view(request):
    return render(request, 'portfolio/educacao.html')

portfolio/templates/portfolio/api.html
{% extends 'portfolio/layout.html' %}

{% block style %}


{% endblock style %}




{% block content %}
    <h3 class="titulo" style="color: white">API's'</h3>


    <div style="display: block;justify-content: center;border-radius: 10px;margin: 20px;background-color: #ffffff;border-bottom-color: #b22121;border-bottom-style: double;box-shadow: rgba(129,29,29,0.8) 5px 5px, rgb(77,19,19) 10px 10px;padding: 15px;">
        <center>
            <div>
                <p class="title" style="color: black; position: absolute;">Coin Flip</p>
                <script>
                    function flipCoin() {
                        const options = {
                            method: 'GET',
                            headers: {
                                'X-RapidAPI-Key': '9ea2f2d1f9mshe369a6605b315d1p1759e4jsn91705e689ef2',
                                'X-RapidAPI-Host': 'coin-flip1.p.rapidapi.com',
                            }
                        };

                        fetch('https://coin-flip1.p.rapidapi.com/headstails', options)
                            .then(response => response.json())
                            .then(data => {
                                document.getElementById('headOrTail').innerHTML = String(data.outcome);
                            });
                    }

                </script>


                <button onclick="flipCoin()">Flip a coin, head or Tails</button>

                <p id="headOrTail" style="color:black"></p>

            </div>
        </center>
    </div>

    <br>

    <div style="display: block;justify-content: center;border-radius: 10px;margin: 20px;background-color: #ffffff;border-bottom-color: #b22121;border-bottom-style: double;box-shadow: rgba(129,29,29,0.8) 5px 5px, rgb(77,19,19) 10px 10px;padding: 15px;">
        <center>
            <div>
                <p class="title" style="color: black; position: absolute;">Weather</p>
                <script>
                    function getTemp() {
                        const options = {
                            method: 'GET',
                            headers: {
                                'X-RapidAPI-Key': '9ea2f2d1f9mshe369a6605b315d1p1759e4jsn91705e689ef2',
                                'X-RapidAPI-Host': 'open-weather13.p.rapidapi.com'
                            }
                        };

                        fetch('https://open-weather13.p.rapidapi.com/city/lisbon', options)
                            .then(response => response.json())
                            .then(data => {
                                const tp = data;
                                document.getElementById('long').innerHTML = String(tp.coord.lon)
                                document.getElementById('lat').innerHTML = String(tp.coord.lat)
                                document.getElementById('id').innerHTML = String(tp.weather[0].id)
                                document.getElementById('temp').innerHTML = String(tp.weather[0].main)
                                document.getElementById('desc').innerHTML = String(tp.weather[0].description)
                                document.getElementById('icon').innerHTML = String(tp.weather[0].icon)



                            });

                    }

                </script>


                <button onclick="getTemp()">Dados de Lisboa</button>

                <p id="long" style="color:black">Longitude </p>
                <p id="lat" style="color:black">Latitude </p>
                <p id="id" style="color:black">ID </p>
                <p id="temp" style="color:black">Temperatura </p>
                <p id="desc" style="color:black">Descrição </p>

            </div>
        </center>
    </div>







{% endblock content %}

portfolio/templates/portfolio/blog.html
<!-- blog.html -->

{% extends 'portfolio/layout.html' %}

{% block style %}

    {% load static %}
    <link rel="stylesheet" href={% static 'portfolio/css/grid.css' %}>

{% endblock style %}



{% block content %}
    <center><h1 style="color: white;">Blog</h1></center>
    {% for post in posts %}
        <div style="display: block;justify-content: center;border-radius: 10px;margin: 20px;background-color: #ffffff;border-bottom-color: #b22121;border-bottom-style: double;box-shadow: rgba(129,29,29,0.8) 5px 5px, rgb(77,19,19) 10px 10px;padding: 15px;">            <h2>
            {{ post.title }}</h2>
            <small>Posted at {{ post.date_added }}</small>
            <p>{{ post.intro }}</p>

            <a href="{% url 'portfolio:post_detail' post.slug %}">Ler mais!</a>
        </div>


    {% endfor %}





{% endblock content %}

portfolio/templates/portfolio/educacao.html
<!-- educação.html -->

{% extends 'portfolio/layout.html' %}

{% block style %}



{% endblock style %}
{% load static %}
<link rel="stylesheet" href={% static 'portfolio/css/educacao.css' %}>

{% block content %}

    <h1 style="color: white">Hero page</h1>
    <center>
        <div style="display: grid;justify-content: center;border-radius: 10px;margin: 20px;background-color: #ffffff;border-bottom-color: #b22121;border-bottom-style: double;box-shadow: rgba(129,29,29,0.8) 5px 5px, rgb(77,19,19) 10px 10px;padding: 15px;">
            <div style="display: -moz-inline-block">
                <h1 class="subtitle">Rodrigo Amaro</h1>
            </div>
            <div style="display: -moz-inline-block">
                <p style="color: black">Olá eu sou o Rodrigo Amaro, estive desde o 9-12 ano na Escola Secundária Maria
                    Amália Vaz Carvalho</p>
                <p style="color: black">Ainda não tenho Curso superior realizado</p>
                <p style="color: black">Ainda não tenho Certificados</p>
            </div>

            <div style="display: -moz-inline-block">

                <p style="color: black"><b style="color: black"><i style="color: black">Aqui estão os meus projetos realizados:
                </i></b><a href={% url 'portfolio:programacao' %}> clica-me!<br><br></a></p>


            </div>


        </div>

        <div style="display: grid;justify-content: center;border-radius: 10px;margin: 20px;background-color: #ffffff;border-bottom-color: #b22121;border-bottom-style: double;box-shadow: rgba(129,29,29,0.8) 5px 5px, rgb(77,19,19) 10px 10px;padding: 15px;">
            <p style="color: black">
                email: bomamo7179@tagbert.com
            </p>
            <br>
            <a style="color: black" href=https://github.com/rodrigoamaro22004525>
                github
            </a>


        </div>
    </center>







{% endblock content %}

portfolio/templates/portfolio/home.html
<!-- home.html -->

{% extends 'portfolio/layout.html' %}


{% block style %}


{% endblock style %}



{% block content %}


    <h2 style="color: white">Bem Vindo ao meu Portfolio!</h2><hr>
    {% if not request.user.is_authenticated %}
    <h3 style="color: red; font-size: 120%">Para aceder a mais coisas precisa de se registar!</h3>
    {% endif %}
    <center><a href="{% url 'portfolio:programacao' %}" ><h2 style="color: white; margin-bottom: 0; font-size: 130%">Programação</h2></a><br></center>

    {% load static %}
    <img class="image" src="{% static 'portfolio/images/Csharp.png' %}" alt="{% url 'portfolio:programacao' %}">

    <br><br><br>

    <center><a href="{% url 'portfolio:virtualizacao' %}" ><h2 style="color: white; margin-bottom: 0; font-size: 130%">Virtualização</h2></a><br></center>

    {% load static %}
    <img class="image" style="width: 100%" src="{% static 'portfolio/images/Containers.png'%} " alt="{% url 'portfolio:virtualizacao' %}">

    <br><br><br>

    <center><a href="{% url 'portfolio:reverse' %}" ><h2 style="color: #ffffff; margin-bottom: 0; font-size: 130%">Reverse-Engeneering (IDA)</h2></a><br></center>

    {% load static %}
    <img class="image" src="{% static 'portfolio/images/revEng.png'%} " alt="{% url 'portfolio:reverse' %}">



{% endblock content %}

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
{% load static %}

<html lang="" style="height: 100%; background: black">




<!--
 Este Portefólio foi feito com o que eu considero um bom portefólio
 se eu quisesse eu teria posto um monte de fotos inúteis e feias
 no (formação) de base, mas prefiro algo "clean" e minimalista, usei algum
 css que não é meu para chegar ao meu objetivo, mas de todas as linhas
 escritas uso muito pouco * estilos.css * e muitas das classes foram
 alteradas, para ficarem conforme o meu portefólio, obviamente
 não está completo, mas fiz tudo de front-end. Com conteúdo original,
 tentei no início fazer tudo como o professor, mas os resultados não
  estavam corretos, logo fiz da minha maneira
 -->

<head>
    <meta charset="UTF-16" name="viewport" content="width=device-width, initial-scale=1">
    <title>Portfolio de Rodrigo Amaro</title>

    {% load static %}
    <link rel="stylesheet" href={% static 'portfolio/css/estilos.css' %}>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/dropdown.css' %}"/>
    <style>label {
        color: white
    }

    body, html {
        height: 100%;
        margin: 0;
    }

    p {
        color: white
    }</style>
</head>
<body class="bg" style="background: black">
<nav class="navbar">
    <div class="navbar-brand">
        <a href="/" class="navbar-item" style="float: left">Rodrigo Amaro </a>
        <div>
            <a class="navbar-item" href={% url 'portfolio:home' %}><strong>Home</strong></a>

            <div class="dropdown">
                <button class="dropbtn" onclick="myFunction()">Formação
                    <i> &#8595;</i>
                </button>
                <div class="dropdown-content" id="myDropdown">
                    <a class="" style=" position: static"
                       href={% url 'portfolio:programacao' %}><strong>Programação</strong></a>
                    <a class="" style=" position: static"
                       href={% url 'portfolio:virtualizacao' %}><strong>virtualizacao</strong></a>
                    <a class="" style=" position: static"
                       href={% url 'portfolio:reverse' %}><strong>reverse_Eng</strong></a>
                </div>
            </div>


            <script>
                /* When the user clicks on the button,
                toggle between hiding and showing the dropdown content */
                function myFunction() {
                    document.getElementById("myDropdown").classList.toggle("show");
                }

                // Close the dropdown if the user clicks outside of it
                window.onclick = function (e) {
                    if (!e.target.matches('.dropbtn')) {
                        var myDropdown = document.getElementById("myDropdown");
                        if (myDropdown.classList.contains('show')) {
                            myDropdown.classList.remove('show');
                        }
                    }
                }
            </script>


            <a class="navbar-item" style="left:180%" href={% url 'portfolio:educacao' %}><strong>Educacao</strong></a>

            <a class="navbar-item" style="left:180%"
               href={% url 'portfolio:licenciatura' %}><strong>Licenciatura</strong></a>


            {% if not request.user.is_authenticated %}
                <a class="navbar-item" style="left:180%" href={% url 'portfolio:login' %}><strong>login</strong></a>
            {% endif %}

            {% if not request.user.is_authenticated %}
                <a class="navbar-item" style="left:180%"
                   href={% url 'portfolio:register' %}><strong>register</strong></a>
            {% endif %}

            {% if request.user.is_authenticated %}
                <a class="navbar-item" style="left:180%" href={% url 'portfolio:logout' %}><strong>logout</strong></a>
            {% endif %}


            {% if request.user.is_authenticated %}
                <a class="navbar-item" style="left:180%" href={% url 'portfolio:api' %}><strong>API</strong></a>
            {% endif %}

            {% if request.user.is_authenticated %}
                <a class="navbar-item" style="left:180%" href={% url 'portfolio:pw' %}><strong>Web</strong></a>
            {% endif %}

            {% if request.user.is_authenticated %}
                <a class="navbar-item" style="left:180%" href=https://pw-lab1-22004525.herokuapp.com/><strong>Outros Labs</strong></a>
            {% endif %}





            <a class="navbar-item" style="left:180%" href={% url 'portfolio:blog' %}><strong>Blog</strong></a>

            {% if request.user.is_authenticated %}
            <a class="navbar-item" style="left:180%" href={% url 'portfolio:quizz' %}><strong>quizz</strong></a>
            {% endif %}



        </div>

    </div>
</nav>

<section class="section" style="background: black">
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</section>


<nav class="navbar" style="overflow: hidden; position:fixed; bottom: 0;width: 100%;margin-top: 50px">
    <div class="navbar-brand">

        <a id="todaysDate" class="navbar-item" style="position:absolute;left: 42%"></a>

        <script>
            function doDate() {
                let str = "";

                const days = ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"];
                const months = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];

                const now = new Date();

                str += "Hoje é: " + days[now.getDay()] + ", " + now.getDate() + " " + months[now.getMonth()] + " " + now.getFullYear() + " " + now.getHours() + ":" + now.getMinutes() + ":" + now.getSeconds();
                document.getElementById("todaysDate").innerHTML = str;
            }

            setInterval(doDate, 1000);
        </script>

        <a style="position: center;" href="https://www.ulusofona.pt/" class="navbar-item">ULHT</a>
    </div>
</nav>
</body>

</html>

portfolio/templates/portfolio/login.html
{% extends 'portfolio/layout.html' %}

{% load static %}
<style>
    .containerLargeAF {


    }


    .containerLargeAF {
        vertical-align: center;
    }
</style>


{% block content %}
    <div  style="">
        <h1 style="color: white"> Login </h1>
        <form method="POST" class="containerLargeAF"
              style="display: block;height: 700px;       border-radius: 10px;        margin: 20px;        background-color: #ffffff;        border-bottom-color: #b22121;        border-bottom-style: double;      box-shadow: rgba(129, 29, 29, 0.8) 5px 5px, rgb(77, 19, 19) 10px 10px;padding-top: 250px;">
            {% csrf_token %}
            <center><p style="color:black;">Login <input type="text" name="username" placeholder=" Username..."></p></center>
            <br><br><br>
            <center><p style="color:black;">Password <input type="password" name="password" placeholder=" Password..."></p></center>
            <br><br><br>
            <center><input class="btn btn-success" type="submit" value="Login"></center>
            <br><br><br>
            <center><p style="color: black">Do not have an account?</p></center>
            <br>
            <center><a style="" href='{% url 'portfolio:register' %}'>Register</a></center>

        </form>
    </div>
{% endblock %}